version: "2"

run:
  timeout: 5m
  go: "1.21"

output:
  formats:
    text:
      path: stdout
      print-issued-lines: true
      print-linter-name: true
      colors: true

formatters:
  enable:
    - gofmt

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - contextcheck
    - dupl
    - durationcheck
    - errname
    - exhaustive
    - forcetypeassert
    - goconst
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - lll
    - makezero
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - rowserrcheck
    - sqlclosecheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace

  settings:
    dupl:
      threshold: 100

    exhaustive:
      default-signifies-exhaustive: true

    goconst:
      min-len: 2
      min-occurrences: 3

    goheader:
      template: ""

    gomodguard:
      blocked:
        modules: []
        versions: []

    gosec:
      severity: medium
      confidence: medium
      excludes:
        - G104
        - G204
        - G304
        - G601

    lll:
      line-length: 120

    misspell:
      locale: US

    nakedret:
      max-func-lines: 30

    nolintlint:
      allow-unused: false
      require-explanation: false
      require-specific: false

    prealloc:
      simple: true
      range-loops: true
      for-loops: false

    staticcheck:
      checks:
        - all
        - -ST1000  # Package comments not required
        - -ST1003  # Naming conventions (allow appId, httpPath, etc.)
        - -ST1005  # Error string punctuation
        - -ST1016  # Receiver name consistency
        - -ST1021  # Comment format on exported types

    thelper:
      test:
        first: true
        name: true
        begin: true
      benchmark:
        first: true
        name: true
        begin: true

    unparam:
      check-exported: false

    whitespace:
      multi-if: false
      multi-func: false

  exclusions:
    generated: strict
    paths:
      - vendor
      - .github
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - dupl
          - gosec
          - goconst
          - noctx
          - forcetypeassert

      - path: test.*\.go
        linters:
          - gosec
          - noctx

      - path: test/testutil/.*\.go
        linters:
          - noctx

      - source: "https?://"
        linters:
          - lll

      # CLI git commands don't need context cancellation
      - path: cmd/gitconfig\.go
        linters:
          - noctx

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
