name: 'Cleanup GitHub App Auth'
description: 'Remove GitHub App authentication configuration (important for non-ephemeral runners)'
branding:
  icon: 'trash-2'
  color: 'red'

inputs:
  force:
    description: 'Force cleanup without confirmation'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Cleanup gh-app-auth configuration
      shell: bash
      run: |
        echo "ðŸ§¹ Cleaning up gh-app-auth configuration..."

        # Check if gh-app-auth is available
        if ! command -v gh &> /dev/null; then
            echo "âš ï¸  GitHub CLI not found, skipping cleanup"
            exit 0
        fi

        if ! gh extension list 2>/dev/null | grep -q "app-auth"; then
            echo "âš ï¸  gh-app-auth extension not found, skipping cleanup"
            exit 0
        fi

        # Remove git credential helper configuration
        echo "ðŸ—‘ï¸  Removing git credential helpers..."
        gh app-auth gitconfig --clean --global 2>/dev/null || true

        # Remove all app configurations
        echo "ðŸ—‘ï¸  Removing app configurations from keyring..."
        if [ "${{ inputs.force }}" == "true" ]; then
            gh app-auth remove --all --force 2>/dev/null || true
        else
            gh app-auth remove --all 2>/dev/null || true
        fi

        echo "âœ… Cleanup complete"
        echo ""
        echo "ðŸ”’ All GitHub App credentials have been removed from:"
        echo "   - Git credential helper configuration"
        echo "   - System keyring/credential storage"
        echo "   - Configuration files"
